/* Auto-generated by genmsg_cpp for file /home/dsolomon/training/ref/2.1/lesson_custom_service/srv/AddTwoInts.srv */
#ifndef LESSON_CUSTOM_SERVICE_SERVICE_ADDTWOINTS_H
#define LESSON_CUSTOM_SERVICE_SERVICE_ADDTWOINTS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace lesson_custom_service
{
template <class ContainerAllocator>
struct AddTwoIntsRequest_ {
  typedef AddTwoIntsRequest_<ContainerAllocator> Type;

  AddTwoIntsRequest_()
  : a(0)
  , b(0)
  {
  }

  AddTwoIntsRequest_(const ContainerAllocator& _alloc)
  : a(0)
  , b(0)
  {
  }

  typedef int64_t _a_type;
  int64_t a;

  typedef int64_t _b_type;
  int64_t b;


  typedef boost::shared_ptr< ::lesson_custom_service::AddTwoIntsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lesson_custom_service::AddTwoIntsRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct AddTwoIntsRequest
typedef  ::lesson_custom_service::AddTwoIntsRequest_<std::allocator<void> > AddTwoIntsRequest;

typedef boost::shared_ptr< ::lesson_custom_service::AddTwoIntsRequest> AddTwoIntsRequestPtr;
typedef boost::shared_ptr< ::lesson_custom_service::AddTwoIntsRequest const> AddTwoIntsRequestConstPtr;


template <class ContainerAllocator>
struct AddTwoIntsResponse_ {
  typedef AddTwoIntsResponse_<ContainerAllocator> Type;

  AddTwoIntsResponse_()
  : sum(0)
  , e(0)
  {
  }

  AddTwoIntsResponse_(const ContainerAllocator& _alloc)
  : sum(0)
  , e(0)
  {
  }

  typedef int64_t _sum_type;
  int64_t sum;

  typedef int64_t _e_type;
  int64_t e;


  typedef boost::shared_ptr< ::lesson_custom_service::AddTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lesson_custom_service::AddTwoIntsResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct AddTwoIntsResponse
typedef  ::lesson_custom_service::AddTwoIntsResponse_<std::allocator<void> > AddTwoIntsResponse;

typedef boost::shared_ptr< ::lesson_custom_service::AddTwoIntsResponse> AddTwoIntsResponsePtr;
typedef boost::shared_ptr< ::lesson_custom_service::AddTwoIntsResponse const> AddTwoIntsResponseConstPtr;

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct AddTwoInts
} // namespace lesson_custom_service

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::lesson_custom_service::AddTwoIntsRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::lesson_custom_service::AddTwoIntsRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::lesson_custom_service::AddTwoIntsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const  ::lesson_custom_service::AddTwoIntsRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::lesson_custom_service::AddTwoIntsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "lesson_custom_service/AddTwoIntsRequest";
  }

  static const char* value(const  ::lesson_custom_service::AddTwoIntsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::lesson_custom_service::AddTwoIntsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 a\n\
int64 b\n\
\n\
";
  }

  static const char* value(const  ::lesson_custom_service::AddTwoIntsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::lesson_custom_service::AddTwoIntsRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::lesson_custom_service::AddTwoIntsResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::lesson_custom_service::AddTwoIntsResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::lesson_custom_service::AddTwoIntsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1f820fa7d431f3397c82aba43bf5f4d3";
  }

  static const char* value(const  ::lesson_custom_service::AddTwoIntsResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1f820fa7d431f339ULL;
  static const uint64_t static_value2 = 0x7c82aba43bf5f4d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::lesson_custom_service::AddTwoIntsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "lesson_custom_service/AddTwoIntsResponse";
  }

  static const char* value(const  ::lesson_custom_service::AddTwoIntsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::lesson_custom_service::AddTwoIntsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 sum\n\
int64 e\n\
\n\
\n\
";
  }

  static const char* value(const  ::lesson_custom_service::AddTwoIntsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::lesson_custom_service::AddTwoIntsResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::lesson_custom_service::AddTwoIntsRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.a);
    stream.next(m.b);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct AddTwoIntsRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::lesson_custom_service::AddTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.sum);
    stream.next(m.e);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct AddTwoIntsResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<lesson_custom_service::AddTwoInts> {
  static const char* value() 
  {
    return "d5e47c59f79a5805249f7e308572c091";
  }

  static const char* value(const lesson_custom_service::AddTwoInts&) { return value(); } 
};

template<>
struct DataType<lesson_custom_service::AddTwoInts> {
  static const char* value() 
  {
    return "lesson_custom_service/AddTwoInts";
  }

  static const char* value(const lesson_custom_service::AddTwoInts&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<lesson_custom_service::AddTwoIntsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d5e47c59f79a5805249f7e308572c091";
  }

  static const char* value(const lesson_custom_service::AddTwoIntsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<lesson_custom_service::AddTwoIntsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "lesson_custom_service/AddTwoInts";
  }

  static const char* value(const lesson_custom_service::AddTwoIntsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<lesson_custom_service::AddTwoIntsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d5e47c59f79a5805249f7e308572c091";
  }

  static const char* value(const lesson_custom_service::AddTwoIntsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<lesson_custom_service::AddTwoIntsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "lesson_custom_service/AddTwoInts";
  }

  static const char* value(const lesson_custom_service::AddTwoIntsResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // LESSON_CUSTOM_SERVICE_SERVICE_ADDTWOINTS_H

